// 12 Business Archetypes based on Carl Jung's Theory
// All names in English for user-facing display

const archetypen = [
  {
    name: "The Sage",
    title: "The Sage",
    shortDescription: "You seek truth and knowledge. Your wisdom helps others understand the world.",
    longDescription: "As a Sage, you are motivated by the desire to understand the world and yourself. You believe that truth and knowledge are the foundation for a fulfilling life. Your analytical skills and quest for insight make you a valued advisor and mentor to others.",
    strength: "Wisdom, intelligence, and analytical abilities",
    fear: "Being deceived or misled",
    motivation: "Understanding the truth and sharing it with others",
    strategy: "Gathering information, analyzing, and developing wisdom",
    weakness: "Can become too academic or indecisive",
    talent: "Wisdom, intelligence, and teaching ability",
    examples: ["Google", "Harvard", "BBC"],
    color: "#4169E1",
    icon: "📚"
  },
  {
    name: "The Visionary",
    title: "The Visionary",
    shortDescription: "You see possibilities where others see limitations. Your imagination shapes the future.",
    longDescription: "As a Visionary, you possess the unique ability to see beyond the present and imagine what could be. You are driven by innovation and the desire to create meaningful change. Your forward-thinking approach inspires others to believe in possibilities they never considered.",
    strength: "Innovation, creativity, and strategic foresight",
    fear: "Mediocrity and stagnation",
    motivation: "Creating transformative change and inspiring others",
    strategy: "Challenging the status quo and envisioning new possibilities",
    weakness: "Can be impractical or disconnected from reality",
    talent: "Vision, innovation, and inspirational leadership",
    examples: ["Tesla", "Apple", "SpaceX"],
    color: "#9370DB",
    icon: "🔮"
  },
  {
    name: "The Builder",
    title: "The Builder",
    shortDescription: "You create lasting structures and systems. Your persistence builds solid foundations.",
    longDescription: "As a Builder, you excel at creating enduring structures, systems, and organizations. You value stability, reliability, and systematic progress. Your methodical approach and attention to detail ensure that what you build stands the test of time.",
    strength: "Structure, reliability, and systematic thinking",
    fear: "Chaos and instability",
    motivation: "Creating lasting value and solid foundations",
    strategy: "Step-by-step construction and systematic planning",
    weakness: "Can be inflexible or resistant to change",
    talent: "Organization, planning, and execution",
    examples: ["IBM", "Ford", "GE"],
    color: "#8B4513",
    icon: "🏗️"
  },
  {
    name: "The Guardian",
    title: "The Guardian",
    shortDescription: "You protect and preserve what matters. Your vigilance ensures safety and continuity.",
    longDescription: "As a Guardian, you are dedicated to protecting people, values, and traditions. You provide security and stability through your careful attention to risks and your commitment to maintaining what is important. Your responsible nature makes others feel safe.",
    strength: "Protection, responsibility, and risk management",
    fear: "Loss and vulnerability",
    motivation: "Ensuring safety and preserving what matters",
    strategy: "Vigilance, preparation, and careful management",
    weakness: "Can be overly cautious or controlling",
    talent: "Security, reliability, and protection",
    examples: ["Volvo", "Allstate", "Norton"],
    color: "#2F4F4F",
    icon: "🛡️"
  },
  {
    name: "The Sovereign",
    title: "The Sovereign",
    shortDescription: "You lead with authority and responsibility. Your control creates order and prosperity.",
    longDescription: "As a Sovereign, you are a natural leader who takes responsibility for creating order and prosperity. You value control, stability, and success. Your ability to make tough decisions and maintain authority inspires respect and creates thriving communities.",
    strength: "Leadership, responsibility, and decision-making",
    fear: "Chaos and loss of control",
    motivation: "Creating a prosperous and stable environment",
    strategy: "Taking control and responsibility for outcomes",
    weakness: "Can be domineering or inflexible",
    talent: "Authority, organization, and resource management",
    examples: ["Microsoft", "Mercedes-Benz", "Rolex"],
    color: "#FFD700",
    icon: "👑"
  },
  {
    name: "The Diplomat",
    title: "The Diplomat",
    shortDescription: "You build bridges and create harmony. Your mediation brings people together.",
    longDescription: "As a Diplomat, you excel at understanding different perspectives and finding common ground. Your ability to navigate complex social situations and mediate conflicts makes you invaluable in creating cooperation and harmony. You believe that connection and understanding can solve most problems.",
    strength: "Communication, mediation, and relationship-building",
    fear: "Conflict and disconnection",
    motivation: "Creating harmony and mutual understanding",
    strategy: "Building bridges and finding win-win solutions",
    weakness: "Can avoid necessary confrontation or be indecisive",
    talent: "Diplomacy, empathy, and negotiation",
    examples: ["LinkedIn", "Airbnb", "UN"],
    color: "#20B2AA",
    icon: "🤝"
  },
  {
    name: "The Catalyst",
    title: "The Catalyst",
    shortDescription: "You spark change and transformation. Your energy accelerates progress.",
    longDescription: "As a Catalyst, you have the unique ability to initiate change and accelerate transformation. You thrive in dynamic environments and excel at getting things moving. Your enthusiasm and ability to see opportunities for change inspire others to take action and embrace new possibilities.",
    strength: "Initiative, energy, and change management",
    fear: "Stagnation and missed opportunities",
    motivation: "Initiating positive change and momentum",
    strategy: "Creating urgency and mobilizing action",
    weakness: "Can be impulsive or impatient",
    talent: "Change initiation, motivation, and momentum-building",
    examples: ["Uber", "Airbnb", "Stripe"],
    color: "#FF6347",
    icon: "⚡"
  },
  {
    name: "The Explorer",
    title: "The Explorer",
    shortDescription: "You seek freedom and adventure. Your curiosity drives you to new horizons.",
    longDescription: "As an Explorer, you are driven by the need for freedom and the urge to have new experiences. You fear confinement and continually seek ways to explore yourself and the world around you. Your adventurous spirit inspires others to step beyond their comfort zones.",
    strength: "Courage for new paths and innovation",
    fear: "Being trapped or restricted",
    motivation: "Having the freedom to be who you truly are",
    strategy: "Traveling, seeking new experiences, and maintaining authenticity",
    weakness: "Can become restless or avoid commitments",
    talent: "Autonomy, individuality, and pioneering spirit",
    examples: ["Jeep", "REI", "The North Face"],
    color: "#228B22",
    icon: "🧭"
  },
  {
    name: "The Alchemist",
    title: "The Alchemist",
    shortDescription: "You transform the ordinary into extraordinary. Your insight reveals hidden potential.",
    longDescription: "As an Alchemist, you possess the rare gift of transformation - turning challenges into opportunities and potential into reality. You see connections others miss and understand how to catalyze growth and change. Your ability to work with unseen forces and patterns makes you a powerful agent of transformation.",
    strength: "Transformation, insight, and pattern recognition",
    fear: "Unintended negative consequences",
    motivation: "Facilitating deep transformation and growth",
    strategy: "Understanding underlying patterns and catalyzing change",
    weakness: "Can be mysterious or misunderstood",
    talent: "Transformation, insight, and manifestation",
    examples: ["Apple", "Pixar", "Disney"],
    color: "#9932CC",
    icon: "🔮"
  },
  {
    name: "The Healer",
    title: "The Healer",
    shortDescription: "You nurture and restore wholeness. Your compassion brings healing and growth.",
    longDescription: "As a Healer, you are dedicated to helping others overcome challenges and find wholeness. You possess deep empathy and the ability to create safe spaces for growth and recovery. Your caring nature and understanding of human needs make you a source of comfort and transformation for others.",
    strength: "Empathy, compassion, and healing presence",
    fear: "Causing harm or being unable to help",
    motivation: "Helping others heal and reach their potential",
    strategy: "Creating safe spaces and providing compassionate support",
    weakness: "Can be overprotective or take on others' pain",
    talent: "Healing, nurturing, and emotional intelligence",
    examples: ["Johnson & Johnson", "Dove", "TOMS"],
    color: "#98FB98",
    icon: "💚"
  },
  {
    name: "The Warrior",
    title: "The Warrior",
    shortDescription: "You face challenges with courage. Your determination overcomes obstacles.",
    longDescription: "As a Warrior, you are courageous, disciplined, and determined to overcome any obstacle. You thrive in competitive situations and are motivated by challenges. Your strength and perseverance inspire others to push beyond their limits and fight for what they believe in.",
    strength: "Courage, discipline, and competitive spirit",
    fear: "Weakness and vulnerability",
    motivation: "Proving competence and achieving victory",
    strategy: "Facing challenges directly and persevering",
    weakness: "Can be aggressive or inflexible",
    talent: "Courage, determination, and resilience",
    examples: ["Nike", "Under Armour", "Red Bull"],
    color: "#DC143C",
    icon: "⚔️"
  },
  {
    name: "The Artisan",
    title: "The Artisan",
    shortDescription: "You create with skill and passion. Your craftsmanship produces excellence.",
    longDescription: "As an Artisan, you are dedicated to mastering your craft and creating work of exceptional quality. You value skill, precision, and the satisfaction of creating something beautiful and functional. Your attention to detail and commitment to excellence set you apart and inspire others to appreciate true craftsmanship.",
    strength: "Skill, precision, and dedication to quality",
    fear: "Creating inferior or mediocre work",
    motivation: "Mastering your craft and creating excellence",
    strategy: "Continuous improvement and attention to detail",
    weakness: "Can be perfectionistic or slow to complete",
    talent: "Craftsmanship, skill development, and quality focus",
    examples: ["Rolex", "Ferrari", "Patagonia"],
    color: "#CD853F",
    icon: "🛠️"
  }
];
